---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: petclinic
            - name: POSTGRES_USER
              value: petclinic
            - name: POSTGRES_PASSWORD
              value: petclinic
