apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://demo-db:5432/petclinic
  SPRING_DATASOURCE_USERNAME: petclinic
  SPRING_DATASOURCE_PASSWORD: petclinic
